# litellm config.yaml for AWS Bedrock

model_list:
  - model_name: claude-3-haiku # A friendly alias you'll use in your API calls
    litellm_params:
      model: "bedrock/anthropic.claude-3-haiku-20240307-v1:0" # The required provider/model_id string
      # AWS credentials will be read from environment variables by default
      aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"
      aws_region_name: "os.environ/AWS_REGION_NAME"

  - model_name: titan-text-lite
    litellm_params:
      model: "bedrock/amazon.titan-text-lite-v1"
      aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"
      aws_region_name: "os.environ/AWS_REGION_NAME"

# Optional general settings
general_settings:
  admin_key: "os.environ/LITELLM_ADMIN_KEY" # For hot reloading

litellm_settings:
  drop_params: True