-- ai-custom-guardrail function: correlation identifiers
--
-- WHY THIS FUNCTION CAN EXIST AT ALL. It was long held that a guardrail
-- function has no request context, because the injectable PARAMETER allowlist
-- is exactly `source`, `content`, `conf`, `resp`. That is true and it is not
-- the whole picture: the allowlist governs what Kong hands the function as an
-- argument, not what the function can reach from its own body. MEASURED
-- (2026-09-14, AI Gateway 2.0.3): inside the body `kong` and `ngx` are tables
-- and `require` is a function, so the PDK is reachable. docs/CREDITS.md records
-- the correction; docs/DESIGN.md section 7 records what it buys.
--
-- WHAT THE TWO IDENTIFIERS MEAN, and they are not interchangeable.
-- MEASURED (2026-09-14) by nine probes sent straight at /v1/scan/sync/request,
-- because no published page settles it and two plausible readings are wrong:
--
--   transaction_id  its own slot. ONE ROUND: a prompt and the response it
--                   produced. Both legs of one exchange must carry the same
--                   value or Strata Cloud Manager shows two unrelated scans.
--   session_id      the CONVERSATION, grouping several rounds.
--   tr_id           NOT a third slot, and NOT the old name of transaction_id.
--                   It is the old name of SESSION_ID: a request carrying only
--                   tr_id comes back with session_id set to that value, a
--                   request carrying only session_id comes back with tr_id set
--                   to it, and when both are sent session_id wins and the
--                   tr_id value is discarded. So sending the round under tr_id
--                   -- the reading the field descriptions invite -- files the
--                   round value in the conversation slot. This function never
--                   sends tr_id.
--
-- Anything not supplied is generated by AIRS as `pan_<uuid>`, which is why an
-- absent identifier is nil here and never an empty string: MEASURED
-- (2026-09-14) a request.body field that is nil is omitted from the payload,
-- while a field that is an empty string is rendered as JSON `false`.
--
-- The round is Kong's own request id, minted on the INPUT leg and stashed in
-- kong.ctx.shared so the OUTPUT leg of the same request reuses it. The
-- conversation can only come from the caller -- a gateway cannot know where a
-- conversation starts -- so it is read from a request header, and falls back to
-- the round so that the two legs of one exchange land in one session rather
-- than two.
--
-- A CAVEAT WORTH STATING. The conversation identifier is caller-supplied, and a
-- caller who controls it can pin it, split it or collide it with someone
-- else's. It is a grouping label for a scan log, not evidence. The round, which
-- is the identifier an investigation actually joins on, is Kong's and cannot be
-- influenced -- unless an operator sets params.transaction_header, which hands
-- that choice to the caller too. Leave it unset unless the calling application
-- is trusted to name its own rounds.
--
-- EVERY PDK CALL IS WRAPPED IN pcall, AND THAT IS NOT DEFENSIVE STYLE.
-- MEASURED (2026-09-14): on the OUTPUT leg of a STREAMED response the function
-- runs with no request context -- kong.request.get_header and ngx.var.request_id
-- both raise, and kong.ctx.shared is a fresh empty table. An unguarded raise
-- there does not fail the request the way a raise on a buffered leg does. It
-- silently skips the guardrail call for that segment: same policy, same
-- streamed request, a function returning a constant produced 7 segment scans,
-- the same function calling kong.request.get_header unguarded produced 0 with
-- HTTP 200 and the whole stream delivered, and wrapping the calls in pcall
-- produced 7 again. An unguarded PDK call in a guardrail function is a silent
-- FAIL-OPEN. Returning an empty table is the correct outcome on that path:
-- both slots are then server-minted and the response scans of a streamed
-- exchange are not grouped with their prompts. Say that plainly rather than
-- inventing a fallback value that would group them wrongly.
return function(conf)
    local ok, shared = pcall(function() return kong.ctx.shared end)
    if not ok or type(shared) ~= "table" then
        return {}
    end
    -- The INPUT leg stashed it; the OUTPUT leg of the same buffered request
    -- reads it back. On a stream this is always a miss -- the stash is fresh.
    if type(shared.airs_correlation) == "table" then
        return shared.airs_correlation
    end

    local function header(name)
        if type(name) ~= "string" or name == "" then
            return nil
        end
        local got, value = pcall(function() return kong.request.get_header(name) end)
        -- The length bound is not cosmetic. This value is caller-supplied and
        -- lands in a security log; a header of arbitrary size has no business
        -- being an identifier.
        if got and type(value) == "string" and #value > 0 and #value <= 256 then
            return value
        end
        return nil
    end

    local params = (conf and conf.params) or {}
    local round = header(params.transaction_header)
    if round == nil then
        local got, request_id = pcall(function() return ngx.var.request_id end)
        if got and type(request_id) == "string" and #request_id > 0 then
            round = request_id
        end
    end
    -- No round means no request context, which means a streamed OUTPUT
    -- segment. Send nothing rather than a conversation with no round in it.
    if round == nil then
        return {}
    end

    local correlation = {
        transaction_id = round,
        session_id = header(params.session_header) or round,
    }
    shared.airs_correlation = correlation
    return correlation
end
